# Generated by Django 4.1 on 2022-12-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_crop_delete_person_delete_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='label',
        ),
    ]
